#Enable track Kinetic Stress
enableTrackStress = false
#Stress multiplier, units SU/(ton x RPM)
#Range: 0.0 ~ 1.0
stressMultiplier = 0.019999999552965164
#Maximum Track RPM, 1 RPM ~ 0.104 m/s
#Range: 1 ~ 1024
maxTrackRPM = 256
#Enable entire tracks being thrown off by explosions
enableTrackThrow = false
