# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Download, Execute Script & Show Tree
        run: |
          echo "Fetching latest release information from Griefed/ServerPackCreator..."
          release_data=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Griefed/ServerPackCreator/releases/latest)
          asset_url=$(echo "$release_data" | jq -r '.assets[] | select(.name | endswith(".sh")) | .browser_download_url')
          if [ -z "$asset_url" ]; then
            echo "No asset ending with .sh found"
            exit 1
          fi
          echo "Downloading script: $asset_url"
          curl -L -o script.sh "$asset_url"
          echo "Executing script with Bash..."
          bash script.sh
          echo "Displaying tree structure:"
          tree .
