# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          check-latest: true
      - name: Run Java Version
        run: java -version
      - name: Download ServerPackCreator
        run: |
          echo "Fetching latest release information from Griefed/ServerPackCreator..."
          release_data=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Griefed/ServerPackCreator/releases/latest)
          asset_url=$(echo "$release_data" | jq -r '.assets | map(select(.name | endswith(".jar") and (contains("javadoc")|not) and (contains("sources")|not) and (contains("api")|not) and (contains("plugin")|not))) | .[0].browser_download_url')
          if [ -z "$asset_url" ]; then
            echo "No asset ending with .jar found satisfying the filter"
            exit 1
          fi
          echo "Downloading jar: $asset_url"
          curl -L -o ServerPackCreator.jar "$asset_url"
          tree .
      - name: Run ServerPackCreator
        run: |
          echo "Executing jar with Java..."
          java -jar ServerPackCreator.jar -cli -config "build/ServerPackCreator.conf" --destination "build/temp"
          echo "Displaying tree structure:"
          tree build/temp
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: build/temp_server_pack.zip
          generate_release_notes: true
          prerelease: true